[workspace]
package.version = "0.1.0"
package.edition = "2021"
package.authors = ["Anuradha Wickramarachchi anuradhawick@gmail.com", "Vijini Mallawaarachchi viji.mallawaarachchi@gmail.com"]

members = ["composition", "coverage", "kmertools", "kmer", "ktio", "counter", "misc"]
resolver = "2"
