[package]
name = "composition"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
kmer = {path = "../kmer"}
ktio = {path = "../ktio"}
memmap2 = "0.9.4"
rayon = "1.10.0"

[dev-dependencies]
os_pipe = "1.1.5"
