[package]
name = "composition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kmer = {path = "../kmer"}
io = {path = "../io"}
memmap2 = "0.9.4"
rayon = "1.10.0"
