[package]
name = "ktio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.6.0"
flate2 = "1.0.28"
memmap2 = "0.9.4"
